apiVersion: v1
kind: Service
metadata:
  labels:
    app: quarkus-crud-reactive-simulation
  name: quarkus-crud-reactive-simulation
spec:
  ports:
  - name: web
    port: 9270
    protocol: TCP
    targetPort: 9270
  selector:
    deployment: quarkus-crud-reactive-simulation
  type: ClusterIP
