apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: quarkus-crud
  name: quarkus-crud-monitor
  namespace: granulate
spec:
  endpoints:
  - interval: 30s
    port: web
    scheme: http
    path: '/q/metrics'
  selector:
    matchLabels:
      app: quarkus-crud
