apiVersion: v1
kind: Service
metadata:
  labels:
    app: quarkus-crud
  name: quarkus-crud
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: quarkus-crud
  type: ClusterIP
