apiVersion: v1
kind: Service
metadata:
  labels:
    app: quarkus-compute
  name: quarkus-compute
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8443-tcp
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: 8778-tcp
    port: 8778
    protocol: TCP
    targetPort: 8778
  selector:
    deployment: quarkus-compute
  type: ClusterIP
