apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: quarkus-compute-simulation
  name: quarkus-compute-simulation-monitor
  namespace: granulate
spec:
  endpoints:
  - interval: 30s
    port: web
    scheme: http
    path: '/q/metrics'
  selector:
    matchLabels:
      app: quarkus-compute-simulation
