apiVersion: v1
kind: Service
metadata:
  labels:
    app: jboss-crud
  name: jboss-crud
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    deployment: jboss-crud
  type: ClusterIP