apiVersion: v1
kind: Service
metadata:
  labels:
    app: jboss-compute-simulation
  name: jboss-compute-simulation
spec:
  ports:
  - name: web
    port: 9270
    protocol: TCP
    targetPort: 9270
  selector:
    deployment: jboss-compute-simulation
  type: ClusterIP
